const data = [
    {
        id: "1",
        title: "Golang Backend Development",
        img: "https://cms.halovina.com/wp-content/uploads/2021/03/golang-web-framework.png",
        price: "200k",
        project:"Create Golang Project.",
        level:"Participants who want to explore and have a career on the back-end with Golang",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"Go is a statically typed, compiled programming language designed at Google by Robert Griesemer, Rob Pike, and Ken Thompson. It is syntactically similar to C, but with memory safety, garbage collection, structural typing, and CSP-style concurrency.",
    },
    {
        id: "2",
        title: "Digital Marketing",
        img: "https://img.freepik.com/free-photo/marketing-strategy-connting-digital-devices-concept_53876-23053.jpg?t=st=1655778776~exp=1655779376~hmac=04d7b5bda87482b37054e25797741856d6f5c6a8171a1657b9dbc2a72ed634fe&w=996",
        price: "200k",
        project:"Create Digital Marketing Strategy Portofolio",
        level:"Participants who want to explore and have a career on Digital Marketing",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"Digital marketing is the component of marketing that uses the Internet and online based digital technologies such as desktop computers, mobile phones and other digital media and platforms to promote products and services.",
    },
    {
        id: "3",
        title: "Flutter Mobile App Development",
        img: "https://img.freepik.com/free-vector/app-development-illustration_52683-47931.jpg?t=st=1655781165~exp=1655781765~hmac=727b356e340e46e8cea20dccab4297ea77355f5a704ceed1dbd46ffb146336da&w=1060",
        price: "200k",
        project:"Create mobile apps with Flutter",
        level:"Participants who want to explore and have a career on Mobile Apps Developer with Flutter Framework",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"Flutter is an open-source UI software development kit created by Google. It is used to develop cross platform applications for Android, iOS, Linux, macOS, Windows, Google Fuchsia, and the web from a single codebase.",
    },
    {
        id: "4",
        title: "Graphic Design",
        img: "https://img.freepik.com/free-vector/designer-girl-concept-illustration_114360-4455.jpg?t=st=1655779745~exp=1655780345~hmac=0671fdcaaa47461c0e6ac854eda872fdcf725b1deebd8865fd41d334dd172cc2&w=740",
        price: "200k",
        project:"Create Graphic Design Portofolio.",
        level:"Participants who want to explore and have a career on Graphic Design",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"Graphic design is the profession and academic discipline whose activity consists in projecting visual communications intended to transmit specific messages to social groups, with specific objectives. Design is based on the principle of form follows a specific function.",
    },
    {
        id: "5",
        title: "Laravel Web Development",
        img: "https://img.freepik.com/free-vector/colourful-illustration-programmer-working_23-2148281410.jpg?t=st=1655781397~exp=1655781997~hmac=e39fedddc8ab45bafc3c7e017f7861fed672c433794d1c4cd684c26d85fe6514&w=740",
        price: "200k",
        project:"Create Website using Laravel Framework",
        level:"Participants who want to explore and have a career on Web Development with Laravel Framework.",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"Laravel is a free, open-source PHP web framework, created by Taylor Otwell and intended for the development of web applications following the model–view–controller architectural pattern and based on Symfony.",
    },
    {
        id: "6",
        title: "React JS Web Frontend",
        img: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
        price: "200k",
        project: "Perfectly make front end web interface using React JS framework",
        level:"Participants who want to explore and have a career on the web front-end with React JS",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc: "React (also known as React.js or ReactJS) is a free and open-source front-end JavaScript library[3] for building user interfaces based on UI components. It is maintained by Meta (formerly Facebook) and a community of individual developers and companies.[4][5][6] React can be used as a base in the development of single-page, mobile, or server-rendered applications with frameworks like Next.js. However, React is only concerned with state management and rendering that state to the DOM, so creating React applications usually requires the use of additional libraries for routing, as well as certain client-side functionality."
    },
    {
        id: "7",
        title: "Phyton - Data Science",
        img: "https://www.freecodecamp.org/news/content/images/size/w2000/2021/08/chris-ried-ieic5Tq8YMk-unsplash.jpg",
        price: "200k",
        project:"Processing Data with Phyton.",
        level:"Participants who want to explore and have a career on Data Science with React JS",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"Python is a high-level, interpreted, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically-typed and garbage-collected.",
    },
    {
        id: "8",
        title: "Wordpress CMS",
        img: "https://asset.kompas.com/crops/XIRnThNLOVyDifBXfEeFqnlc4eU=/58x69:596x427/750x500/data/photo/2020/09/02/5f4f9f977b550.jpg",
        price: "200k",
        project:"Create Wordpress Page.",
        level:"Participants who want to explore and have a career on Wordpress Developer",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"WordPress is a free and open-source content management system written in PHP and paired with a MySQL or MariaDB database. Features include a plugin architecture and a template system, referred to within WordPress as Themes.",
    },
    {
        id: "9",
        title: "Machine Learning",
        img: "https://stekom.ac.id/images/infoprogdi/bsr/13a438f1e89f111f5871e6f43eb23b2d.jpg",
        price: "200k",
        project:"Create simple algorithm machine learning.",
        level:"Participants who want to explore and have a career on Machine Learning.",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"Machine learning (ML) is a field of inquiry devoted to understanding and building methods that 'learn', that is, methods that leverage data to improve performance on some set of tasks.",
    },
    {
        id: "10",
        title: "Vue JS Web Frontend",
        img: "https://cdn-media-1.freecodecamp.org/ghost/2019/03/vueart.png",
        price: "200k",
        project:"Create front-end with Vue.js",
        level:"Participants who want to explore and have a career on Frontend with Vue.js.",
        period:"The learning period for this class is 1 month, with an estimated 6 hours per day",
        desc:"Vue.js is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications. It was created by Evan You, and is maintained by him and the rest of the active core team members.",
    }
]

export default data;